version: "3.9"

services:
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=paicavi
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=${DB_PORT-5432}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d paicavi"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
